version: "3.6"
services:
  mongodb:
    image3: mongo:6.0.1
    container_name: mongodb
    volumes:
      - ${PWD}/db/mongo:/data/db
    ports:
      - 27018:27017
    networks:
      - default
    restart: always
